preset-change-interval: 20m

presets:
  1:
    trade-item: PISTON
    amount: 64
    required-items:
      - "1 NETHERITE_INGOT"
  2:
    trade-item: OBSIDIAN
    amount: 32
    required-items:
      - "16 DIAMOND"
  3:
    trade-item: GOLDEN_APPLE
    amount: 8
    required-items:
      - "32 GOLD_INGOT"

messages:
  no-required-items: "&cYou don't have the required items to trade!"
  inventory-full: "&cYour inventory is full!"
  trade-success: "&fYou successfully traded for &#7afc00%amount%x %item%&f!"
  reset: "&#ff9900&lBILLFORD &8» &fThe trades have reset! New trade: &#7afc00%amount%x %item%&f."
  reload: "&aBillford configuration reloaded."
  time-changed: "&aBillford reset time changed to &f%time%&a."
  trade-added: "&aAdded trade &f#%number%&a."
  trade-updated: "&aUpdated trade &f#%number%&a."
  trade-removed: "&aRemoved trade &f#%number%&a."

sounds:
  trade-success: ENTITY_PLAYER_LEVELUP
  error: ENTITY_VILLAGER_NO
